# Generated by Django 3.1 on 2020-10-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='username',
        ),
    ]
