# Generated by Django 3.1 on 2020-10-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0002_remove_blogdata_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBlogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewTitle', models.CharField(max_length=200)),
                ('NewDescription', models.TextField()),
                ('NewImage', models.ImageField(default='default.jpg', upload_to='blog_pics/')),
                ('NewHashtag', models.CharField(max_length=200)),
                ('Newusername', models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
